name: testapp

services:
  web:
    env_var: PORT
    protocol: http
    hostname: testapp.test
  postgres:
    env_var: DB_PORT
    preferred_port: 5432

computed:
  CORS_ORIGINS:
    value: "${web.url}"
    env_file: .env
